# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ulrich Says
tagline:          'A Jekyll theme'
description:      'This is where Ross (aka) writes about important and not so important life matters.'
#url:              http://hyde.getpoole.com
baseurl:          https://rjattrill.github.io/hyde/

author:
  name:           'Ross Attrill'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
