# Dependencies
#markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ulrich Says
tagline:          'Life matters'
description:      'This is where Ross (aka) Ulrich writes about important and not so important life matters.'
url:              https://rjattrill.github.io/life/
baseurl:          https://rjattrill.github.io/life/

author:
  name:           'Ross Attrill'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rjattrill/life
